### ISSUE TITLE
No LCD causes error

### ISSUE THREAD

**Issue by rienheuver** [alexmacrae/SamplerBox#3]
The system currently doesn't support having no LCD at all. If you set both config options to false:
`USE_HD44780_16X2_LCD = False`
`USE_HD44780_20x4_LCD = False`
The system will crash on startup. This is (so far) only on debian (raspi) with system mode 2.

After some searching through the code, this happens with the following traceback:
`HD44780_sys_2.py, line 44`
`HD44780_sys_2.py, line 56`
`{ some error about lcd not having a function clear() }`
Because lcd wasn't instantiated since both options were set to false.

I think putting line 44 through 47 in an if-block would solve it, but I'm not familiar enough with the software yet to be sure it doens't break anything else. I'll be trying this out later.

**Comment by rienheuver** [comment]
A workaround for now is to set
`USE_HD44780_16X2_LCD = True`
and
`SYSTEM_MODE = 1`.
For some reason, it will then not complain about a missing LCD. I haven't figured out yet why it works with one LCD set to true.

**Comment by alexmacrae** [comment]
@rienheuver the system doesn't actually know if an LCD is connected or not - but what all this is needed for is the console feedback. I've emulated what you would otherwise see on the LCD, on one line in the console. If both are False then this causes issues. 

I'm thinking I may remove 20x4 support as there's a lot more work to be done to fill each of those 4 lines. I don't find myself needing more than a 16x2 module. It also means I can remove those two USE_HD44780 lines in the config.ini - which now seems unnecessary, and causes issues for users such as yourself!

**Comment by rienheuver** [comment]
I haven't been able to try out the system with the LCD yet (have only been messing with software so far, hardware comes later this month), but it seems to me like 20x4 could mostly be useful for menu navigation. If that's fine the way it is, your solution sound good to me.

**Comment by rienheuver** [comment]
Just noticed this when closing samplerbox and having no lcd attached:

    Stopped by CTRL-C
    
    >>>> Closing sounddevice stream
    Traceback (most recent call last):
      File "samplerbox.py", line 242, in <module>
        gv.sysfunc.shutdown(log_file)
      File "/root/SamplerBox/modules/systemfunctions.py", line 127, in shutdown
        gv.displayer.LCD_SYS.lcd.close(clear=False) # does GPIO.cleanup()
    AttributeError: LCD_SYS_1 instance has no attribute 'lcd'

So your fix would definitely solve a problem, but it's not a very clean solution to what's wrong.

**Comment by sachithgithu** [comment]
please help me bro
